# config.yaml

# -----------------
# Database settings
# -----------------

# -----------------
# API Keys & URLs
# -----------------


# -----------------
# Ingestion settings
# -----------------

# -----------------
# ML / Training settings
# -----------------

# -----------------
# HPC / Slurm settings
# -----------------
